Name: OR-tools
Description: links LightGBM.
Version: null

Requires: protobuf re2

Cflags: >
    -I/opt/ac_install/include

Libs: >
    -L/opt/ac_install/lib
    -Wl,-R/opt/ac_install/lib

    -lortools
    -lCbc
    -lCbcSolver
    -lCgl
    -lClp
    -lClpSolver
    -lCoinUtils
    -lGLPK
    -lOsi
    -lOsiCbc
    -lOsiClp
    -lhighs
    -lscip
    -lz
