title: "AtCoder Language Update 2024.11.: C++23 (GCC 14.2.0) [draft]"

plugins:
    - jemoji
    - jekyll-redirect-from

description: |
    The contents of this repository are temporary proposal.
    提案段階のものです．すべてが採択されるわけではありません．

theme: jekyll-theme-cayman
